Contact form
Wikitelmex/Portfolio pull request #3
Opened 2021-08-17 19:55 UTC by Wikitelmex

# Contact form
- add contact form
- add contact form styel
- add social icon bars to contact form
- styling social bar and background

2021-08-17 21:02 UTC, karvel-code requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All your linter checks pass successfully.

## Required Changes ♻️
_Check the comments under the review._

- [x] Please eliminate the dark part appearing on the right edge of the form section as it is not provided in the Figma design.
![image](https://user-images.githubusercontent.com/52443674/129800011-a89683ea-d209-47bb-a26c-4aabf7209ea9.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-17 21:02 UTC, karvel-code commented on index.html
> +                <form name="contact-form" class="portfolio-form" action="https://formspree.io/f/mnqlovey">
- [x] Please ensure you add the attribute `method = "POST" `. It is important as it tells the web browser how to send form data to a server.

2021-08-17 21:02 UTC, karvel-code commented on index.html
> +                </form>
- [x] Your form does not submit data successfully. The issue could be that the attribute method = "POST" is missing. I'd advise you first to add it and test if your form works well when valid data is submitted.

2021-08-17 21:02 UTC, karvel-code commented on index.html
> +                        <textarea class="textarea" name="contact-textarea" cols="30" rows="10"></textarea>
- [x] Please add a placeholder attribute for the `textarea` tag. It's important as it informs the user what is expected of him/her.
- [x] Please add the `required` attribute for the `textarea` tag. It enhances the validations for the input.

2021-08-17 21:02 UTC, karvel-code commented on index.html
> +                    <input class="textbox" type="text" placeholder="Full name" required>
- [x] Please add a `maxlength="30"` attribute for the name input tag. It is important in order to limit the number of characters(in this case to 30) a user can input for this input tag.

2021-08-17 21:02 UTC, karvel-code commented on index.html
> +                        <textarea class="textarea" name="contact-textarea" cols="30" rows="10"></textarea>
- [x] Please add a `maxlength="500"` attribute for the textarea tag

2021-08-18 14:55 UTC, Wikitelmex commented on index.html
> +                </form>
- modifications added and started to work well

2021-08-18 15:26 UTC, AshakaE approved these changes
### Hi @Wikitelmex  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-18 15:33 UTC, merged